apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acm
  description: cfhighlander acm component
  labels:
    cfhighlander/component: acm
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-acm
    github.com/project-slug: theonestack/hl-component-acm
    cfhighlander/latest-version: '1.4.4'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander