apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alb-cognitio
  description: cfhighlander alb-cognitio component
  labels:
    cfhighlander/component: alb-cognitio
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-alb-cognitio
    github.com/project-slug: theonestack/hl-component-alb-cognitio
    cfhighlander/latest-version: '0.0.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander