apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: amazonmq
  description: cfhighlander amazonmq component
  labels:
    cfhighlander/component: amazonmq
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-amazonmq
    github.com/project-slug: theonestack/hl-component-amazonmq
    cfhighlander/latest-version: '1.3.3'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander