apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: amp-ecs
  description: cfhighlander amp-ecs component
  labels:
    cfhighlander/component: amp-ecs
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-amp-ecs
    github.com/project-slug: theonestack/hl-component-amp-ecs
    cfhighlander/latest-version: '0.1.5'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander