apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apigateway-rest
  description: cfhighlander apigateway-rest component
  labels:
    cfhighlander/component: apigateway-rest
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-apigateway-rest
    github.com/project-slug: theonestack/hl-component-apigateway-rest
    cfhighlander/latest-version: '0.1.6'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander