apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asg-v2
  description: cfhighlander asg-v2 component
  labels:
    cfhighlander/component: asg-v2
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-asg-v2
    github.com/project-slug: theonestack/hl-component-asg-v2
    cfhighlander/latest-version: '0.5.1'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander