apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aurora-postgres
  description: cfhighlander aurora-postgres component
  labels:
    cfhighlander/component: aurora-postgres
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-aurora-postgres
    github.com/project-slug: theonestack/hl-component-aurora-postgres
    cfhighlander/latest-version: '2.4.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander