apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aurora-mysql
  description: cfhighlander aurora-mysql component
  labels:
    cfhighlander/component: aurora-mysql
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-aurora-mysql
    github.com/project-slug: theonestack/hl-component-aurora-mysql
    cfhighlander/latest-version: '3.6.3'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander