apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: client-vpn
  description: cfhighlander client-vpn component
  labels:
    cfhighlander/component: client-vpn
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-client-vpn
    github.com/project-slug: theonestack/hl-component-client-vpn
    cfhighlander/latest-version: '0.3.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander