apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudfront
  description: cfhighlander cloudfront component
  labels:
    cfhighlander/component: cloudfront
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-cloudfront
    github.com/project-slug: theonestack/hl-component-cloudfront
    cfhighlander/latest-version: '0.8.3'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander