apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cognito-userpool-client
  description: cfhighlander cognito-userpool-client component
  labels:
    cfhighlander/component: cognito-userpool-client
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-cognito-userpool-client
    github.com/project-slug: theonestack/hl-component-cognito-userpool-client
    cfhighlander/latest-version: '0.1.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander