apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cognito
  description: cfhighlander cognito component
  labels:
    cfhighlander/component: cognito
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-cognito
    github.com/project-slug: theonestack/hl-component-cognito
    cfhighlander/latest-version: '1.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander