apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: documentdb
  description: cfhighlander documentdb component
  labels:
    cfhighlander/component: documentdb
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-documentdb
    github.com/project-slug: theonestack/hl-component-documentdb
    cfhighlander/latest-version: '0.4.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander