apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecs-task
  description: cfhighlander ecs-task component
  labels:
    cfhighlander/component: ecs-task
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-ecs-task
    github.com/project-slug: theonestack/hl-component-ecs-task
    cfhighlander/latest-version: '0.5.11'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander