apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eks-cluster
  description: cfhighlander eks-cluster component
  labels:
    cfhighlander/component: eks-cluster
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-eks-cluster
    github.com/project-slug: theonestack/hl-component-eks-cluster
    cfhighlander/latest-version: '0.6.5'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander