apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elasticache-memcache
  description: cfhighlander elasticache-memcache component
  labels:
    cfhighlander/component: elasticache-memcache
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-elasticache-memcache
    github.com/project-slug: theonestack/hl-component-elasticache-memcache
    cfhighlander/latest-version: '0.1.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander