apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elasticsearch
  description: cfhighlander elasticsearch component
  labels:
    cfhighlander/component: elasticsearch
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-elasticsearch
    github.com/project-slug: theonestack/hl-component-elasticsearch
    cfhighlander/latest-version: '0.4.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander