apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fargate-v2
  description: cfhighlander fargate-v2 component
  labels:
    cfhighlander/component: fargate-v2
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-fargate-v2
    github.com/project-slug: theonestack/hl-component-fargate-v2
    cfhighlander/latest-version: '0.8.6'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander