apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: glue-job
  description: cfhighlander glue-job component
  labels:
    cfhighlander/component: glue-job
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-glue-job
    github.com/project-slug: theonestack/hl-component-glue-job
    cfhighlander/latest-version: '0.1.3'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander