apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kms
  description: cfhighlander kms component
  labels:
    cfhighlander/component: kms
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-kms
    github.com/project-slug: theonestack/hl-component-kms
    cfhighlander/latest-version: '0.2.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander