apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lambda
  description: cfhighlander lambda component
  labels:
    cfhighlander/component: lambda
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-lambda
    github.com/project-slug: theonestack/hl-component-lambda
    cfhighlander/latest-version: '1.0.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander