apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lambda-edge
  description: cfhighlander lambda-edge component
  labels:
    cfhighlander/component: lambda-edge
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-lambda-edge
    github.com/project-slug: theonestack/hl-component-lambda-edge
    cfhighlander/latest-version: '0.1.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander