apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lib-iam
  description: cfhighlander lib-iam component
  labels:
    cfhighlander/component: lib-iam
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-lib-iam
    github.com/project-slug: theonestack/hl-component-lib-iam
    cfhighlander/latest-version: '0.2.1'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander