apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rds-proxy
  description: cfhighlander rds-proxy component
  labels:
    cfhighlander/component: rds-proxy
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-rds-proxy
    github.com/project-slug: theonestack/hl-component-rds-proxy
    cfhighlander/latest-version: '0.1.1'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander