apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rds-replica
  description: cfhighlander rds-replica component
  labels:
    cfhighlander/component: rds-replica
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-rds-replica
    github.com/project-slug: theonestack/hl-component-rds-replica
    cfhighlander/latest-version: '0.1.3'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander