apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rds-mssql
  description: cfhighlander rds-mssql component
  labels:
    cfhighlander/component: rds-mssql
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-rds-mssql
    github.com/project-slug: theonestack/hl-component-rds-mssql
    cfhighlander/latest-version: '0.2.5'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander