apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redshift
  description: cfhighlander redshift component
  labels:
    cfhighlander/component: redshift
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-redshift
    github.com/project-slug: theonestack/hl-component-redshift
    cfhighlander/latest-version: '0.1.9'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander