apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3-deployer
  description: cfhighlander s3-deployer component
  labels:
    cfhighlander/component: s3-deployer
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-s3-deployer
    github.com/project-slug: theonestack/hl-component-s3-deployer
    cfhighlander/latest-version: '0.1.7'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander