apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3
  description: cfhighlander s3 component
  labels:
    cfhighlander/component: s3
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-s3
    github.com/project-slug: theonestack/hl-component-s3
    cfhighlander/latest-version: '1.7.6'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander