apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sftp
  description: cfhighlander sftp component
  labels:
    cfhighlander/component: sftp
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-sftp
    github.com/project-slug: theonestack/hl-component-sftp
    cfhighlander/latest-version: '2.6.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander