apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-ad
  description: cfhighlander simple-ad component
  labels:
    cfhighlander/component: simple-ad
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-simple-ad
    github.com/project-slug: theonestack/hl-component-simple-ad
    cfhighlander/latest-version: '0.3.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander