apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: site-to-site-vpn
  description: cfhighlander site-to-site-vpn component
  labels:
    cfhighlander/component: site-to-site-vpn
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-site-to-site-vpn
    github.com/project-slug: theonestack/hl-component-site-to-site-vpn
    cfhighlander/latest-version: '0.1.1'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander