apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sns
  description: cfhighlander sns component
  labels:
    cfhighlander/component: sns
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-sns
    github.com/project-slug: theonestack/hl-component-sns
    cfhighlander/latest-version: '1.3.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander