apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sqs
  description: cfhighlander sqs component
  labels:
    cfhighlander/component: sqs
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-sqs
    github.com/project-slug: theonestack/hl-component-sqs
    cfhighlander/latest-version: '1.5.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander