apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: transit-gateway
  description: cfhighlander transit-gateway component
  labels:
    cfhighlander/component: transit-gateway
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-transit-gateway
    github.com/project-slug: theonestack/hl-component-transit-gateway
    cfhighlander/latest-version: '0.1.6'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander