apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vpc
  description: cfhighlander vpc component
  labels:
    cfhighlander/component: vpc
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-vpc
    github.com/project-slug: theonestack/hl-component-vpc
    cfhighlander/latest-version: '2.6.0'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander