apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wafv2
  description: cfhighlander wafv2 component
  labels:
    cfhighlander/component: wafv2
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-wafv2
    github.com/project-slug: theonestack/hl-component-wafv2
    cfhighlander/latest-version: '0.2.2'
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander